### Matrix 

In [3]:
A<- matrix(data= c(78,2,13,1,3,13,1,45,78),nrow =3,ncol=3,byrow = TRUE)
A

[,1] [,2] [,3]
[1,] 78    2   13  
[2,]  1    3   13  
[3,]  1   45   78

In [5]:
rbind(-1:7,0:8)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
[1,] -1   0    1    2    3    4    5    6    7   
[2,]  0   1    2    3    4    5    6    7    8

In [7]:
cbind(-1:7,0:8)

[,1] [,2]
 [1,] -1   0   
 [2,]  0   1   
 [3,]  1   2   
 [4,]  2   3   
 [5,]  3   4   
 [6,]  4   5   
 [7,]  5   6   
 [8,]  6   7   
 [9,]  7   8

## Dimension

In [9]:
dim(A)

[1] 3 3

In [11]:
nrow(A)

[1] 3

In [13]:
ncol(A)

[1] 3

In [16]:
dim(A)[2]

[1] 3

## Extract elements of a matrix

In [19]:
print(A[3,3])

[1] 78


In [21]:
print(A[,c(2,1)])

     [,1] [,2]
[1,]    2   78
[2,]    3    1
[3,]   45    1


In [23]:

print(A[2,])

[1]  1  3 13


In [25]:

print(A[,2])

[1]  2  3 45


In [27]:

print(A[2:4])

[1] 1 1 2


## matrix manipulations

In [29]:

print(A[,-1])

     [,1] [,2]
[1,]    2   13
[2,]    3   13
[3,]   45   78


In [31]:

print(A[-1,-2])

     [,1] [,2]
[1,]    1   13
[2,]    1   78


In [34]:

b<-A
b

[,1] [,2] [,3]
[1,] 78    2   13  
[2,]  1    3   13  
[3,]  1   45   78

In [37]:

b[c(2,3),2:1]<-c(99,0,1,2)
print(b)

     [,1] [,2] [,3]
[1,]   78    2   13
[2,]    1   99   13
[3,]    2    0   78


In [41]:
diag(x=b)<-rep(x=0,times=1)


In [42]:

print(b)

     [,1] [,2] [,3]
[1,]    0    2   13
[2,]    1    0   13
[3,]    2    0    0
