In [4]:
A <- matrix(c(1, 8,5, 2), ncol = 2, byrow = TRUE)
A

[,1] [,2]
[1,] 1    8   
[2,] 5    2

In [8]:

AtA <- t(A) %*% A
AtA

[,1] [,2]
[1,] 26   18  
[2,] 18   68

In [10]:
AtA2 <- crossprod(A)
AtA2

[,1] [,2]
[1,] 26   18  
[2,] 18   68

In [12]:

356*A

[,1] [,2]
[1,]  356 2848
[2,] 1780  712

## Linear Combinations

In [15]:
3.4*A- 1.2*A

[,1] [,2]
[1,]  2.2 17.6
[2,] 11.0  4.4

In [17]:
5*A + 4*A

[,1] [,2]
[1,]  9   72  
[2,] 45   18

## Solve()

In [20]:
y <- matrix(nrow=3 , ncol=3,byrow=T,data=c(1,2,3,3,4,5,4,5,1))
y

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 3    4    5   
[3,] 4    5    1

In [22]:
solve(y)

[,1] [,2] [,3]
[1,] -2.1  1.3 -0.2
[2,]  1.7 -1.1  0.4
[3,] -0.1  0.3 -0.2

In [24]:
y %*% solve(y)

[,1]          [,2]         [,3]         
[1,]  1.000000e+00 0.000000e+00 -1.110223e-16
[2,] -8.326673e-16 1.000000e+00  1.110223e-16
[3,] -3.469447e-16 1.665335e-16  1.000000e+00

## Eigen values and Eigen Vectors

In [25]:

eigen(y)

eigen() decomposition
$values
[1]  9.6360956 -3.3238808 -0.3122148

$vectors
           [,1]       [,2]        [,3]
[1,] -0.3707376 -0.3861027 -0.76622760
[2,] -0.7189333 -0.4069940  0.63636323
[3,] -0.5879528  0.8278167 -0.08909043
